version: "3"
services:
  php-web:
    container_name: katr_prom_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    user: 1000:1000
    ports:
      - 80:80
  mysql:
    container_name: katr_prom_mysql
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "secret"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "secret"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  mysql_admin:
    container_name: katr_prom_myadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: 'mysql'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
volumes:
  mysqldata: {}
